<?php
/**
 * @file
 * A simple color field module with a color picker.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function colorfield_minicolors_form_field_ui_field_edit_form_alter(&$form, $form_state) {
  // Exposes the new color picker.
  if ($form['#field']['type'] == 'colorfield' && $form['#instance']['widget']['type'] == 'colorfield_unified_textfield') {
    $form['instance']['widget']['settings']['colorfield_options']['colorfield_colorpicker_type']['#options']['minicolors'] = t('Minicolors');
    // If jQuery update is here, no need to suggest to the user to get it.
    $form['instance']['widget']['settings']['colorfield_options']['colorfield_colorpicker_type']['#description'] = '';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function colorfield_minicolors_field_widget_colorfield_unified_textfield_form_alter(&$element, &$form_state, $context) {
  // Attaches the library to the field based on the selected colorpicker.
  $settings = $context['instance']['widget']['settings'];
  if (isset($settings['colorfield_options']['colorfield_enable_colorpicker']) && $settings['colorfield_options']['colorfield_colorpicker_type'] == 'minicolors') {
    $element['rgb']['#attached'] = array(
      'library' => array(array('colorfield_minicolors', 'minicolors')),
      'js' => array(drupal_get_path('module', 'colorfield_minicolors') . '/js/colorfield-minicolors.js'),
    );
  }
}

/**
 * Implements hook_library().
 */
function colorfield_minicolors_library() {
  return array(
    'minicolors' => array(
      'title' => t('jQuery Minicolors'),
      'website' => 'http://labs.abeautifulsite.net/jquery-miniColors/',
      'version' => '2.0.0-beta3',
      'js' => array(
        drupal_get_path('module', 'colorfield_minicolors') . '/lib/jquery.minicolors.js' => array('group' => JS_LIBRARY),
      ),
      'css' => array(
        drupal_get_path('module', 'colorfield_minicolors') . '/lib/jquery.minicolors.css' => array(
          'type' => 'file',
          'media' => 'screen',
        ),
      ),
      'dependencies' => array(
        // Require jQuery UI core by System module.
        array('system', 'jquery'),
      ),
    ),
  );
}
